
--
-- Table structure for table period
--

DROP TABLE IF EXISTS period;


CREATE TABLE period (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  startDate DATE DEFAULT NULL,
  endDate DATE DEFAULT NULL,
  id_season BIGINT DEFAULT NULL,
  FOREIGN KEY (id_season) REFERENCES season(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);


--
-- Dumping data for table convention
--

INSERT INTO convention VALUES (43,'Nessuna Convenzione','Nessuna Convenzione','thisconventionshouldntneverberemoved',2);
